png("plot3.png", width = 480, height=480)
pcolr <- c("black","red","blue")
plot(x = jat$timestamp, y = jat$Sub_metering_1, ylab = "Energy sub meeting",type="l",col = pcolr[1],ylim=c(0,38),xlab="")
par(new =T)
plot(x = jat$timestamp, y = jat$Sub_metering_2, ylab = "Energy sub meeting",type="l",col = pcolr[2],ylim=c(0,38),xlab="")
par(new =T)
plot(x = jat$timestamp, y = jat$Sub_metering_3, ylab = "Energy sub meeting",type="l",col = pcolr[3],ylim=c(0,38),xlab="")
legend("topright",legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=pcolr, lwd=1, xjust = 1)
par(new=F)
dev.off()